# https://hub.docker.com/_/mysql variables de entorno
version: "3"
services:
  db:
    image: mysql
    container_name: MYSQL
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "admin"
    volumes: 
    # Persiste los datos en la carpeta schemas a traves del biding
      - ./schemas:/var/lib/mysql